flavor = 'fig pie'
print(flavor[0:3])
print(flavor[3:7])
print(flavor[3:])
print(flavor[:])
print(flavor[:14])
print(flavor[13:15])
print(flavor[-7:-4])
print(flavor[-7:0])
print(flavor[-7])
print(flavor[-3:])